version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"                # chemin du package.json
    schedule:
      interval: "weekly"          # daily | weekly | monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
